# Proyecto Slotting

## Objetivos

Realizar una simulación de los pedidos de un determinado centro de distribución.

## Variables a considerar

Estas son variables que van a influir al momento de ver los tiempos de congestión.

* Números de pickeadores
* Velocidad de los pickeadores
* Tiempo que se demora en sacar el producto objetivo
* etc.

## Supuestos

Para efectos práticos, puede reducir la complejidad del problema con lo siguiente:

* Todos los productos pueden ser alojado en cualquier slots del centro de distribución
* Los slots pueden albergar solo un solo producto
* La velocidad de los pickeadores es contante
* Todos los pickeadores ocupan la misma máquina
* etc.

## Lectura de datos

Lectura de los principales datos del problema

**observación**: Debe tener instalado las librerías de `pandas`, `numpy` y `xlrd`.

In [32]:
# librerias
import pandas as pd
import numpy

### Información general

Detalles de los conjuntos de datos utilizados

In [33]:
diccionario = pd.read_csv("data/diccionario.csv",sep=',') 
diccionario

,Dataset,Columna,Descripcion
0,layout,Producto,identificador del producto
1,layout,orden,orden secuencial del producto
2,layout,pasillo,identificador del pasillo
3,layout,uso,tipo de uso
4,layout,direccion,"dirección del pasillo (ASCENDENTE, DESCENDENTE..."
5,layout,gondola,gondola izquierda o derecha
6,layout,slot_largo,largo del slot
7,layout,slot_ancho,ancho del slot
8,layout,slot_alto,alto del slot
9,layout,largo_pasillo,largo del pasillo
10,layout,ancho_pasillo,ancho del pasillo
11,adyacencia,pasillo,identificador del pasillo (p)
12,adyacencia,adyacente,identificador del pasillo adyacente (pa)
13,adyacencia,distancia,distancia del pasillo al pasillo adyacente (p→pa)
14,skus,Producto,identificador del producto
15,skus,Largo,largo del producto
16,skus,Ancho,ancho del producto
17,skus,Alto,alto del producto
18,skus,Peso,peso del producto
19,skus,Apilabilidad,tipo de apilabilidad
20,ots,Pedido,identificador del pedido
21,ots,Cod.Prod,identificador del producto

### Layout

<img src="images/esquema.png" alt="Girl in a jacket" width="700" height="700">

In [ ]:
xlsx_file = "data/layout.xlsx"

In [11]:
# layout
df_layout = pd.read_excel(xlsx_file, sheet_name="layout")
df_layout.head()

,Producto,orden,pasillo,uso,direccion,gondola,slot_largo,slot_ancho,slot_alto,largo_pasillo,ancho_pasillo
0,1,1,11,Pallet Pck General,ASCENDENTE,izquierda,9999,9999,9999,9999,9999
1,2,2,11,Pallet Pck General,ASCENDENTE,derecha,9999,9999,9999,9999,9999
2,3,3,11,Pallet Pck General,ASCENDENTE,izquierda,9999,9999,9999,9999,9999
3,4,4,11,Pallet Pck General,ASCENDENTE,derecha,9999,9999,9999,9999,9999
4,5,5,11,Pallet Pck General,ASCENDENTE,izquierda,9999,9999,9999,9999,9999

In [12]:
# adyacencia
adyacencia = pd.read_excel(xlsx_file, sheet_name="adyacencia")
adyacencia.head()

   pasillo  adyacente  distancia
0        0       11.0        1.0
1        0       31.0        1.0
2        0       51.0        1.0
3       11       12.0        1.0
4       11       21.0        1.0

### Skus

In [15]:
skus = pd.read_csv("data/sku.csv",sep=',') 
skus.head()

   Producto  Largo  Ancho  Alto  Peso  Apilabilidad
0         1      1      1     1     1             1
1         2      1      1     1     1             1
2         3      1      1     1     1             1
3         4      1      1     1     1             1
4         5      1      1     1     1             1

### Ordenes de trabajo

In [16]:
ots = pd.read_csv("data/ot.csv",sep=',') 
ots.head()

   Pedido  Cod.Prod
0       1       9.0
1       2      69.0
2       2      42.0
3       2      44.0
4       2      27.0